service: seoul-demo-reminder

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    IS_LOCAL: ${env:IS_LOCAL}
    MONGO_DB_USERNAME: ${env:MONGO_DB_USERNAME}
    MONGO_DB_PASSWORD: ${env:MONGO_DB_PASSWORD}
    MONGO_DB_HOST: ${env:MONGO_DB_HOST}
    SQS_AWS_ACCESS_KEY: ${env:SQS_AWS_ACCESS_KEY}
    SQS_AWS_SECRET_ACCESS_KEY: ${env:SQS_AWS_SECRET_ACCESS_KEY}
    SQS_AWS_REGION: ${env:SQS_AWS_REGION}
    SQS_URL: ${env:SQS_URL}
    EMAIL_SENDER_ADDRESS: ${env:EMAIL_SENDER_ADDRESS}
    EMAIL_SENDER_PASSWORD: ${env:EMAIL_SENDER_PASSWORD}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudformation:Describe*
        - cloudformation:List*
        - cloudformation:Get*
        - cloudformation:CreateStack
        - cloudformation:UpdateStack
        - cloudformation:DeleteStack
        - cloudformation:CreateChangeSet
        - cloudformation:ExecuteChangeSet
        - cloudformation:DeleteChangeSet
        - cloudformation:ValidateTemplate
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:*
      Resource: '*'
    - Effect: Allow
      Action:
        - s3:CreateBucket
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:DeleteBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        # @see https://github.com/serverless/serverless/issues/5919
        - s3:GetEncryptionConfiguration
        - s3:PutEncryptionConfiguration
        - s3:DeleteBucketPolicy
      Resource: '*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:DeleteLogGroup
        - logs:CreateLogStream
        - logs:DeleteLogStream
        - logs:PutLogEvents
        - logs:DescribeLogGroups
        - logs:DescribeLogStreams
        - logs:TagResource
      Resource: '*'
    - Effect: Allow
      Action:
        - apigateway:GET
        - apigateway:POST
        - apigateway:PUT
        - apigateway:DELETE
      Resource: '*'
    - Effect: Allow
      Action:
        - iam:GetRole
        - iam:DeleteRolePolicy
        - iam:CreateRole
        - iam:DeleteRole
        - iam:PutRolePolicy
        - iam:PassRole
      Resource: '*'
    - Effect: Allow
      Action:
        - states:*
      Resource: '*'
    - Effect: Allow
      Action:
        - mongodb:*
      Resource: '*'
    - Effect: Allow
      Action:
        - events:*
      Resource: '*'
    - Effect: Allow
      Action:
        - sqs:*
      Resource: '*'

functions:
  # 1시간마다 실행되는 스케줄러
  main:
    handler: src/handler.main
    events:
      - schedule: rate(30 minutes)
      # 개발용 엔드포인트
      - http:
          path: main
          method: get
          cors: true
    # sqs 로 email 알림을 보내는 함수
  sendEmail:
    handler: src/handler.sendEmail
    timeout: 30
    events:
      - sqs:
          arn: ${env:SQS_AWS_ARN}
          batchSize: 1
          enabled: true
      - http:
          path: send-email
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-tscpaths

custom:
  dotenv:
    path: .env.prod
